services:
  - type: web
    name: autodocugen-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: OLLAMA_API_BASE
        value: https://your-ollama-instance.com  # You'll need to update this 